[package]
name = "id3"
version = "0.0.1"
authors = ["James Hurst <jamesrhurst@users.noreply.github.com>"]

[dependencies.audiotag]
git = "https://github.com/jamesrhurst/rust-audiotag.git"

[dependencies.phf]
git = "https://github.com/sp3d/rust-phf.git"

[dependencies.phf_mac]
git = "https://github.com/sp3d/rust-phf.git"

[dependencies.id3_macros]
path = "macros"
